# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1dd2c269cd7c65d0ff9bd4e99f50cadbf9ddd13d3b1eb631a7e21762abe3885d2aeb9f4d55f7a43d43fa092ac4a47396cd58ee088e31f3dbb9b6c36f4aa05de

test:
  secret_key_base: b639520505476c9768e64dbb1269caaa6c3bd409a124d784017c99193dc52bcf6d466bd0f429ddc423e60907b500819991841955727e8551f2397b547ab32b16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
